package com.kojingji.task.dao;

import com.kojingji.task.models.MemberPayRecord;

public interface MemberPayRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_pay_record
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_pay_record
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int insert(MemberPayRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_pay_record
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int insertSelective(MemberPayRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_pay_record
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	MemberPayRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_pay_record
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int updateByPrimaryKeySelective(MemberPayRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_pay_record
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int updateByPrimaryKey(MemberPayRecord record);
}