package com.kojingji.task.dao;

import java.util.Map;

import com.kojingji.task.models.Registration;

public interface RegistrationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registration
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registration
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int insert(Registration record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registration
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int insertSelective(Registration record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registration
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	Registration selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registration
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int updateByPrimaryKeySelective(Registration record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registration
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int updateByPrimaryKey(Registration record);

	Registration selectByQqIdAndCid(Map<String, Object> paramMap);
}