package com.kojingji.task.dao;

import com.kojingji.task.models.Sysitemvalue;

public interface SysitemvalueMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysitemvalue
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysitemvalue
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int insert(Sysitemvalue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysitemvalue
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int insertSelective(Sysitemvalue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysitemvalue
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	Sysitemvalue selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysitemvalue
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int updateByPrimaryKeySelective(Sysitemvalue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysitemvalue
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int updateByPrimaryKey(Sysitemvalue record);
}