package com.kojingji.task.dao;

import java.util.List;
import java.util.Map;

import com.kojingji.task.models.Task;

public interface TaskMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table campaign
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table campaign
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int insert(Task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table campaign
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int insertSelective(Task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table campaign
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	Task selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table campaign
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int updateByPrimaryKeySelective(Task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table campaign
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	int updateByPrimaryKey(Task record);
	
	int selectByPageCount(Map<String,Object> paramMap);
	List<Task> selectByPageList(Map<String,Object> paramMap);
}