package com.kojingji.task.models;

import java.util.Date;

public class Category {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.name
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.code
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.parent_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Long parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.create_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.id
	 * @return  the value of category.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.id
	 * @param id  the value for category.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.name
	 * @return  the value of category.name
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.name
	 * @param name  the value for category.name
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.code
	 * @return  the value of category.code
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.code
	 * @param code  the value for category.code
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.parent_id
	 * @return  the value of category.parent_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Long getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.parent_id
	 * @param parentId  the value for category.parent_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.create_time
	 * @return  the value of category.create_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.create_time
	 * @param createTime  the value for category.create_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}