package com.kojingji.task.models;

import java.util.Date;

public class Member {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.qq_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String qqId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.nick_name
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String nickName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.mobile
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.email
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.qq
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String qq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.wechat
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String wechat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.last_login_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Date lastLoginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.last_update_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Date lastUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.register_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Date registerTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.alipay_account
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String alipayAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.wechat_account
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String wechatAccount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.id
	 * @return  the value of member.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.id
	 * @param id  the value for member.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.qq_id
	 * @return  the value of member.qq_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getQqId() {
		return qqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.qq_id
	 * @param qqId  the value for member.qq_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setQqId(String qqId) {
		this.qqId = qqId == null ? null : qqId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.nick_name
	 * @return  the value of member.nick_name
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.nick_name
	 * @param nickName  the value for member.nick_name
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName == null ? null : nickName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.mobile
	 * @return  the value of member.mobile
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.mobile
	 * @param mobile  the value for member.mobile
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.email
	 * @return  the value of member.email
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.email
	 * @param email  the value for member.email
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.qq
	 * @return  the value of member.qq
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.qq
	 * @param qq  the value for member.qq
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setQq(String qq) {
		this.qq = qq == null ? null : qq.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.wechat
	 * @return  the value of member.wechat
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getWechat() {
		return wechat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.wechat
	 * @param wechat  the value for member.wechat
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setWechat(String wechat) {
		this.wechat = wechat == null ? null : wechat.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.last_login_time
	 * @return  the value of member.last_login_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.last_login_time
	 * @param lastLoginTime  the value for member.last_login_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.last_update_time
	 * @return  the value of member.last_update_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.last_update_time
	 * @param lastUpdateTime  the value for member.last_update_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.register_time
	 * @return  the value of member.register_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Date getRegisterTime() {
		return registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.register_time
	 * @param registerTime  the value for member.register_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.alipay_account
	 * @return  the value of member.alipay_account
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getAlipayAccount() {
		return alipayAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.alipay_account
	 * @param alipayAccount  the value for member.alipay_account
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setAlipayAccount(String alipayAccount) {
		this.alipayAccount = alipayAccount == null ? null : alipayAccount
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.wechat_account
	 * @return  the value of member.wechat_account
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getWechatAccount() {
		return wechatAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.wechat_account
	 * @param wechatAccount  the value for member.wechat_account
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setWechatAccount(String wechatAccount) {
		this.wechatAccount = wechatAccount == null ? null : wechatAccount
				.trim();
	}
}