package com.kojingji.task.models;

import java.util.Date;

public class MemberPayRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_pay_record.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_pay_record.t_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Integer tId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_pay_record.record_date
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Date recordDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_pay_record.payer_qq_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Integer payerQqId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_pay_record.payer_account
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String payerAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_pay_record.payee_qq_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Integer payeeQqId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_pay_record.payee_account
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String payeeAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_pay_record.pay_status
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String payStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_pay_record.pay_type
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String payType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_pay_record.pay_mode
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String payMode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_pay_record.pay_money
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Integer payMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_pay_record.apply_pay_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Date applyPayTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_pay_record.finish_pay_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Date finishPayTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_pay_record.pay_serial_no
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String paySerialNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_pay_record.remark
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_pay_record.id
	 * @return  the value of member_pay_record.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_pay_record.id
	 * @param id  the value for member_pay_record.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_pay_record.t_id
	 * @return  the value of member_pay_record.t_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Integer gettId() {
		return tId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_pay_record.t_id
	 * @param tId  the value for member_pay_record.t_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void settId(Integer tId) {
		this.tId = tId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_pay_record.record_date
	 * @return  the value of member_pay_record.record_date
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Date getRecordDate() {
		return recordDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_pay_record.record_date
	 * @param recordDate  the value for member_pay_record.record_date
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setRecordDate(Date recordDate) {
		this.recordDate = recordDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_pay_record.payer_qq_id
	 * @return  the value of member_pay_record.payer_qq_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Integer getPayerQqId() {
		return payerQqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_pay_record.payer_qq_id
	 * @param payerQqId  the value for member_pay_record.payer_qq_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setPayerQqId(Integer payerQqId) {
		this.payerQqId = payerQqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_pay_record.payer_account
	 * @return  the value of member_pay_record.payer_account
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getPayerAccount() {
		return payerAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_pay_record.payer_account
	 * @param payerAccount  the value for member_pay_record.payer_account
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setPayerAccount(String payerAccount) {
		this.payerAccount = payerAccount == null ? null : payerAccount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_pay_record.payee_qq_id
	 * @return  the value of member_pay_record.payee_qq_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Integer getPayeeQqId() {
		return payeeQqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_pay_record.payee_qq_id
	 * @param payeeQqId  the value for member_pay_record.payee_qq_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setPayeeQqId(Integer payeeQqId) {
		this.payeeQqId = payeeQqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_pay_record.payee_account
	 * @return  the value of member_pay_record.payee_account
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getPayeeAccount() {
		return payeeAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_pay_record.payee_account
	 * @param payeeAccount  the value for member_pay_record.payee_account
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setPayeeAccount(String payeeAccount) {
		this.payeeAccount = payeeAccount == null ? null : payeeAccount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_pay_record.pay_status
	 * @return  the value of member_pay_record.pay_status
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getPayStatus() {
		return payStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_pay_record.pay_status
	 * @param payStatus  the value for member_pay_record.pay_status
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setPayStatus(String payStatus) {
		this.payStatus = payStatus == null ? null : payStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_pay_record.pay_type
	 * @return  the value of member_pay_record.pay_type
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_pay_record.pay_type
	 * @param payType  the value for member_pay_record.pay_type
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setPayType(String payType) {
		this.payType = payType == null ? null : payType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_pay_record.pay_mode
	 * @return  the value of member_pay_record.pay_mode
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getPayMode() {
		return payMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_pay_record.pay_mode
	 * @param payMode  the value for member_pay_record.pay_mode
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setPayMode(String payMode) {
		this.payMode = payMode == null ? null : payMode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_pay_record.pay_money
	 * @return  the value of member_pay_record.pay_money
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Integer getPayMoney() {
		return payMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_pay_record.pay_money
	 * @param payMoney  the value for member_pay_record.pay_money
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setPayMoney(Integer payMoney) {
		this.payMoney = payMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_pay_record.apply_pay_time
	 * @return  the value of member_pay_record.apply_pay_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Date getApplyPayTime() {
		return applyPayTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_pay_record.apply_pay_time
	 * @param applyPayTime  the value for member_pay_record.apply_pay_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setApplyPayTime(Date applyPayTime) {
		this.applyPayTime = applyPayTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_pay_record.finish_pay_time
	 * @return  the value of member_pay_record.finish_pay_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Date getFinishPayTime() {
		return finishPayTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_pay_record.finish_pay_time
	 * @param finishPayTime  the value for member_pay_record.finish_pay_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setFinishPayTime(Date finishPayTime) {
		this.finishPayTime = finishPayTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_pay_record.pay_serial_no
	 * @return  the value of member_pay_record.pay_serial_no
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getPaySerialNo() {
		return paySerialNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_pay_record.pay_serial_no
	 * @param paySerialNo  the value for member_pay_record.pay_serial_no
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setPaySerialNo(String paySerialNo) {
		this.paySerialNo = paySerialNo == null ? null : paySerialNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_pay_record.remark
	 * @return  the value of member_pay_record.remark
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_pay_record.remark
	 * @param remark  the value for member_pay_record.remark
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}