package com.kojingji.task.models;

import java.util.Date;

public class PlayRoom {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column play_room.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column play_room.t_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Long tId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column play_room.p_index
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Integer pIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column play_room.p_count
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Integer pCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column play_room.create_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column play_room.update_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column play_room.create_by
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column play_room.update_by
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String updateBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column play_room.id
	 * @return  the value of play_room.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column play_room.id
	 * @param id  the value for play_room.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column play_room.t_id
	 * @return  the value of play_room.t_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Long gettId() {
		return tId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column play_room.t_id
	 * @param tId  the value for play_room.t_id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void settId(Long tId) {
		this.tId = tId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column play_room.p_index
	 * @return  the value of play_room.p_index
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Integer getpIndex() {
		return pIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column play_room.p_index
	 * @param pIndex  the value for play_room.p_index
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setpIndex(Integer pIndex) {
		this.pIndex = pIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column play_room.p_count
	 * @return  the value of play_room.p_count
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Integer getpCount() {
		return pCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column play_room.p_count
	 * @param pCount  the value for play_room.p_count
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setpCount(Integer pCount) {
		this.pCount = pCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column play_room.create_time
	 * @return  the value of play_room.create_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column play_room.create_time
	 * @param createTime  the value for play_room.create_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column play_room.update_time
	 * @return  the value of play_room.update_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column play_room.update_time
	 * @param updateTime  the value for play_room.update_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column play_room.create_by
	 * @return  the value of play_room.create_by
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column play_room.create_by
	 * @param createBy  the value for play_room.create_by
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy == null ? null : createBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column play_room.update_by
	 * @return  the value of play_room.update_by
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column play_room.update_by
	 * @param updateBy  the value for play_room.update_by
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy == null ? null : updateBy.trim();
	}
}