package com.kojingji.task.models;

public class Sysitemvalue {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysitemvalue.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysitemvalue.item_key
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String itemKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysitemvalue.item_key_des
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String itemKeyDes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysitemvalue.item_name
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String itemName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysitemvalue.item_value
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String itemValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysitemvalue.order_num
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Integer orderNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysitemvalue.type
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysitemvalue.remark
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysitemvalue.enable
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String enable;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysitemvalue.id
	 * @return  the value of sysitemvalue.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysitemvalue.id
	 * @param id  the value for sysitemvalue.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysitemvalue.item_key
	 * @return  the value of sysitemvalue.item_key
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getItemKey() {
		return itemKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysitemvalue.item_key
	 * @param itemKey  the value for sysitemvalue.item_key
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setItemKey(String itemKey) {
		this.itemKey = itemKey == null ? null : itemKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysitemvalue.item_key_des
	 * @return  the value of sysitemvalue.item_key_des
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getItemKeyDes() {
		return itemKeyDes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysitemvalue.item_key_des
	 * @param itemKeyDes  the value for sysitemvalue.item_key_des
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setItemKeyDes(String itemKeyDes) {
		this.itemKeyDes = itemKeyDes == null ? null : itemKeyDes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysitemvalue.item_name
	 * @return  the value of sysitemvalue.item_name
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getItemName() {
		return itemName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysitemvalue.item_name
	 * @param itemName  the value for sysitemvalue.item_name
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setItemName(String itemName) {
		this.itemName = itemName == null ? null : itemName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysitemvalue.item_value
	 * @return  the value of sysitemvalue.item_value
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getItemValue() {
		return itemValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysitemvalue.item_value
	 * @param itemValue  the value for sysitemvalue.item_value
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setItemValue(String itemValue) {
		this.itemValue = itemValue == null ? null : itemValue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysitemvalue.order_num
	 * @return  the value of sysitemvalue.order_num
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Integer getOrderNum() {
		return orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysitemvalue.order_num
	 * @param orderNum  the value for sysitemvalue.order_num
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysitemvalue.type
	 * @return  the value of sysitemvalue.type
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysitemvalue.type
	 * @param type  the value for sysitemvalue.type
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysitemvalue.remark
	 * @return  the value of sysitemvalue.remark
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysitemvalue.remark
	 * @param remark  the value for sysitemvalue.remark
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysitemvalue.enable
	 * @return  the value of sysitemvalue.enable
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getEnable() {
		return enable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysitemvalue.enable
	 * @param enable  the value for sysitemvalue.enable
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setEnable(String enable) {
		this.enable = enable == null ? null : enable.trim();
	}
}