package com.kojingji.task.models;

import java.util.Date;

public class Task {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.name
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.image
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String image;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.remark
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.category
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Long category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.status
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.regist_max
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Integer registMax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.regist_is_charge
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Long registIsCharge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.regist_fee
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Long registFee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.regist_end_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Date registEndTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.is_can_cancel
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Integer isCanCancel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.can_cancel_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Date canCancelTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.is_pay
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Integer isPay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.pay_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Date payTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.is_online
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Integer isOnline;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.is_live
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Integer isLive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.live_url
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String liveUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.create_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.update_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.create_by
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column campaign.update_by
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	private String updateBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.id
	 * @return  the value of campaign.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.id
	 * @param id  the value for campaign.id
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.name
	 * @return  the value of campaign.name
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.name
	 * @param name  the value for campaign.name
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.image
	 * @return  the value of campaign.image
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getImage() {
		return image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.image
	 * @param image  the value for campaign.image
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setImage(String image) {
		this.image = image == null ? null : image.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.remark
	 * @return  the value of campaign.remark
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.remark
	 * @param remark  the value for campaign.remark
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.category
	 * @return  the value of campaign.category
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Long getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.category
	 * @param category  the value for campaign.category
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setCategory(Long category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.status
	 * @return  the value of campaign.status
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.status
	 * @param status  the value for campaign.status
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.regist_max
	 * @return  the value of campaign.regist_max
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Integer getRegistMax() {
		return registMax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.regist_max
	 * @param registMax  the value for campaign.regist_max
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setRegistMax(Integer registMax) {
		this.registMax = registMax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.regist_is_charge
	 * @return  the value of campaign.regist_is_charge
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Long getRegistIsCharge() {
		return registIsCharge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.regist_is_charge
	 * @param registIsCharge  the value for campaign.regist_is_charge
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setRegistIsCharge(Long registIsCharge) {
		this.registIsCharge = registIsCharge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.regist_fee
	 * @return  the value of campaign.regist_fee
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Long getRegistFee() {
		return registFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.regist_fee
	 * @param registFee  the value for campaign.regist_fee
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setRegistFee(Long registFee) {
		this.registFee = registFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.regist_end_time
	 * @return  the value of campaign.regist_end_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Date getRegistEndTime() {
		return registEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.regist_end_time
	 * @param registEndTime  the value for campaign.regist_end_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setRegistEndTime(Date registEndTime) {
		this.registEndTime = registEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.is_can_cancel
	 * @return  the value of campaign.is_can_cancel
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Integer getIsCanCancel() {
		return isCanCancel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.is_can_cancel
	 * @param isCanCancel  the value for campaign.is_can_cancel
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setIsCanCancel(Integer isCanCancel) {
		this.isCanCancel = isCanCancel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.can_cancel_time
	 * @return  the value of campaign.can_cancel_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Date getCanCancelTime() {
		return canCancelTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.can_cancel_time
	 * @param canCancelTime  the value for campaign.can_cancel_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setCanCancelTime(Date canCancelTime) {
		this.canCancelTime = canCancelTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.is_pay
	 * @return  the value of campaign.is_pay
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Integer getIsPay() {
		return isPay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.is_pay
	 * @param isPay  the value for campaign.is_pay
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setIsPay(Integer isPay) {
		this.isPay = isPay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.pay_time
	 * @return  the value of campaign.pay_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.pay_time
	 * @param payTime  the value for campaign.pay_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.is_online
	 * @return  the value of campaign.is_online
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Integer getIsOnline() {
		return isOnline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.is_online
	 * @param isOnline  the value for campaign.is_online
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setIsOnline(Integer isOnline) {
		this.isOnline = isOnline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.is_live
	 * @return  the value of campaign.is_live
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Integer getIsLive() {
		return isLive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.is_live
	 * @param isLive  the value for campaign.is_live
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setIsLive(Integer isLive) {
		this.isLive = isLive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.live_url
	 * @return  the value of campaign.live_url
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getLiveUrl() {
		return liveUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.live_url
	 * @param liveUrl  the value for campaign.live_url
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setLiveUrl(String liveUrl) {
		this.liveUrl = liveUrl == null ? null : liveUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.create_time
	 * @return  the value of campaign.create_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.create_time
	 * @param createTime  the value for campaign.create_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.update_time
	 * @return  the value of campaign.update_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.update_time
	 * @param updateTime  the value for campaign.update_time
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.create_by
	 * @return  the value of campaign.create_by
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.create_by
	 * @param createBy  the value for campaign.create_by
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy == null ? null : createBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column campaign.update_by
	 * @return  the value of campaign.update_by
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column campaign.update_by
	 * @param updateBy  the value for campaign.update_by
	 * @mbggenerated  Tue Oct 04 23:02:17 CST 2016
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy == null ? null : updateBy.trim();
	}
}